### ISSUE TITLE
libc.prctl not available, the process name will be python and not x-tile

### ISSUE THREAD

**Issue by fabfer** [giuspen/x-tile#22]
Hallo,

I'm having the following issue on a fresh installation of Ubuntu 22.04.1 LTS:

WM = GNOME Shell
libc.prctl not available, the process name will be python and not x-tile
DEBUG warning _NET_CURRENT_DESKTOP improperly set
Traceback (most recent call last):
  File "/usr/share/x-tile/modules/core.py", line 1048, in tile_horizontally
    tilings.tile_horizontally(checked_windows_list, glob.monitors_areas, self.get_dest_ws())
  File "/usr/share/x-tile/modules/tilings.py", line 49, in tile_horizontally
    tile_horizontally_on_area(windows_list[0],
  File "/usr/share/x-tile/modules/tilings.py", line 162, in tile_horizontally_on_area
    support.moveresize(checked_window, x + win_num*step, y, step, h, dws)
  File "/usr/share/x-tile/modules/support.py", line 197, in moveresize
    dest_workspace = glob.ret_pointer[0]
ValueError: NULL pointer access

Any idea how to solve the issue?
Thanks in advance, and by the way the application is really great!

Best regards,
FAbrizio

**Comment by giuspen** [comment]
Hello Fabrizio, the real issue here is `DEBUG warning _NET_CURRENT_DESKTOP improperly set` and the reason is that your Ubuntu 22.04 runs on Wayland and not Xorg.
x-tile is built strictly for Xorg (that's where the x comes from).
You can change your Ubuntu to run on Xorg as follows: https://askubuntu.com/questions/1410256/how-do-i-use-x-instead-of-wayland-on-22-04
